name: Auto Post to Pinterest

on:
  schedule:
    - cron: '*/30 * * * *'  # Har 30 minute me run hoga
  workflow_dispatch:       # Manual trigger option

jobs:
  auto-post:
    runs-on: ubuntu-latest

    steps:
    - name: Repository clone karein
      uses: actions/checkout@v2

    - name: PHP install karein
      run: sudo apt-get install -y php-cli

    - name: Pinterest pe post karein
      run: php script.php

    - name: Debugging ke liye log check karein
      if: failure()
      run: cat error.log

    - name: GitHub Action complete
      run: echo "🎯 Auto-posting workflow complete!"

# Yeh workflow automatically WordPress post ko fetch karega aur Pinterest pe dal dega!
# Ab bas GitHub pe push karein, aur aapki automation ready hai. 🚀
